version: 0.2

env:
  variables:
    # <maven模块目录名>（仅包含模块路径；repo 名取路径最后一层）
    MODULES: "test/demo-user-rpc test/demo-order-rpc test/demo-web-api"

phases:
  install:
    runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - 'echo "Resolve build version"'
      - 'COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-8)'
      - 'export BUILD_VERSION=${BUILD_VERSION:-$COMMIT_HASH}'
      - '[ -z "$BUILD_VERSION" ] && export BUILD_VERSION=latest || true'
      - 'echo "BUILD_VERSION=$BUILD_VERSION"'

      - 'echo "Compose REPO_PREFIX and login to ECR"'
      - 'export AWS_REGION="${AWS_REGION:-$AWS_DEFAULT_REGION}"'
      - 'export AWS_ACCOUNT_ID="${AWS_ACCOUNT_ID:-$(aws sts get-caller-identity --query Account --output text)}"'
      - 'export REPO_PREFIX="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"'
      - 'echo "REPO_PREFIX=$REPO_PREFIX"'

      - 'aws sts get-caller-identity'
      - 'aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$REPO_PREFIX"'

  build:
    commands:
      - 'echo "Maven build all modules"'
      - 'mvn -B -DskipTests clean package'
      - 'echo "Build & push Docker images"'
      - 'set -e'
      - 'echo "MODULES=$MODULES"'
      - |
        for MODULE in $MODULES; do
          MODULE="${MODULE%/}"                       # 去掉末尾 /
          REPO_PATH="${MODULE##*/}"                 # 取路径最后一层作为 repo 名
          MODULE_DIR="./$MODULE"
          DF="$MODULE_DIR/docker/Dockerfile"        # 优先使用 docker/Dockerfile
          CTX="$MODULE_DIR"

          # 如果 docker/Dockerfile 不存在，回退到模块根目录的 Dockerfile
          if [ ! -f "$DF" ] && [ -f "$MODULE_DIR/Dockerfile" ]; then
            DF="$MODULE_DIR/Dockerfile"
          fi

          echo "MODULE=$MODULE"
          echo "REPO_PATH=$REPO_PATH"
          echo "DF=$DF"
          echo "CTX=$CTX"

          IMAGE_BASE="$REPO_PREFIX/$REPO_PATH"
          IMAGE_TAG="$IMAGE_BASE:$BUILD_VERSION"

          # 确保 ECR 仓库存在（已有则忽略错误）
          aws ecr describe-repositories --repository-names "$REPO_PATH" --region "$AWS_REGION" >/dev/null 2>&1 || \
          aws ecr create-repository   --repository-name   "$REPO_PATH" --region "$AWS_REGION" >/dev/null 2>&1 || true

          # 1) 路径/文件存在性检查
          [ -d "$MODULE_DIR" ] || { echo "ERROR: MODULE_DIR not found: $MODULE_DIR"; exit 2; }
          [ -f "$DF" ] || { echo "ERROR: Dockerfile not found: $DF"; exit 3; }

          # 2) 至少存在一个可运行 JAR（排除 sources/javadoc/tests）
          find "$MODULE_DIR/target" -maxdepth 1 -type f -name "*.jar" \
            ! -name "*-sources.jar" ! -name "*-javadoc.jar" ! -name "*-tests.jar" \
            | head -n1 | grep -q . || { echo "ERROR: No runnable jar under $MODULE_DIR/target"; exit 4; }

          echo "==> BUILD $MODULE -> $IMAGE_TAG (DF=$DF, CTX=$CTX)"
          docker build -t "$IMAGE_TAG" -f "$DF" "$CTX" || { echo "ERROR: docker build failed for $MODULE"; exit 5; }

          echo "==> PUSH $IMAGE_TAG"
          docker push "$IMAGE_TAG" || { echo "ERROR: push failed for $IMAGE_TAG"; exit 6; }

          echo "==> TAG & PUSH latest"
          docker tag "$IMAGE_TAG" "$IMAGE_BASE:latest" || { echo "ERROR: tag latest failed"; exit 7; }
          docker push "$IMAGE_BASE:latest"              || { echo "ERROR: push latest failed"; exit 8; }
        done

  post_build:
    commands:
      - 'echo "DONE: Build version $BUILD_VERSION pushed to ECR"'