AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodePipeline: per-service ECS deploy (GitHub via CodeStar, CodeBuild builds image, CFN deploys ECS stack)'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: { default: "✅ 必填参数（必须提供）" }
        Parameters:
          - PipelineName
          - ServiceName
          - SdRegistryId
          - RepoName
      - Label: { default: "🧩 选填参数（有默认值，可覆盖）" }
        Parameters:
          - BranchName
          - ModulePath
    ParameterLabels:
      # ✅ 必填参数
      PipelineName: { default: "Pipeline 名称（CI/CD 流水线标识）" }
      ServiceName: { default: "服务名（ServiceBase，例如 demo-user-rpc）" }
      SdRegistryId: { default: "Cloud Map Service ID" }
      RepoName: { default: "GitHub 仓库（org/repo）" }

      # 🧩 选填参数
      BranchName: { default: "代码分支名称（默认 main）" }
      ModulePath: { default: "多模块项目下的构建模块路径（如 services/demo-user-rpc）" }

Parameters:

  # =========================================================
  # ✅ 必填参数（无默认值，必须传入）
  # =========================================================

  # --- 服务基础信息 ---
  PipelineName:
    Type: String
    Description: 'Pipeline 名称（例如 deploy-<service>）'

  ServiceName:
    Type: String
    Description: '服务名（= ServiceBase，例如 demo-user-rpc）'

  SdRegistryId:
    Type: String
    Description: 'Cloud Map Service ID（例如 srv-xxxx）'

  RepoName:
    Type: String
    Description: 'GitHub 仓库全名（org/repo）'

  # =========================================================
  # 🧩 选填参数（默认值，可覆盖）
  # =========================================================

  # --- 源码与模板 ---
  BranchName:
    Type: String
    Default: 'main'
    Description: 'Git 分支名（默认 main）'
  ModulePath:
    Type: String
    Default: "."
    Description: '模块路径，如 services/demo-user-rpc'

  # =========================================================
  # 🧩 未开放参数（默认值，不可覆盖）
  # =========================================================
  # --- 源码来源（GitHub via CodeStar Connections）---
  ConnectionArn:
    Type: String
    Default: 'arn:aws:codeconnections:us-east-1:297997107448:connection/9adfd918-2843-4147-9bc9-c4ee1a99bc39'
    Description: 'CodeStar Connections ARN（GitHub 连接）'

  ArtifactBucketName:
    Type: String
    Default: 'codepipeline-us-east-1-3622cd43956e-4d23-9284-a18746ff6c07'
    Description: '存放Pipeline Artifacts的S3桶名'

  TemplatePath:
    Type: String
    Default: 'ci/ecs-service-deploy.yaml'
    Description: 'ECS 部署模板路径'

  BuildSpec:
    Type: String
    Default: 'ci/buildspec.yaml'
    Description: 'CodeBuild构建文件路径'

  ContainerImage:
    Type: String
    Default: 'aws/codebuild/standard:7.0'
    Description: '容器镜像'

  # --- 固定角色 ---
  CloudFormationDeployRoleArn:
    Type: String
    Default: 'arn:aws:iam::297997107448:role/CloudFormationDeployRole'
    Description: 'CloudFormation 执行角色 ARN（由 CodePipeline 的 CFN Action 假设）'

  CodePipelineRoleArn:
    Type: String
    Default: 'arn:aws:iam::297997107448:role/CodePipelineRole'
    Description: 'CodePipeline Service Role ARN'

  CodeBuildRoleArn:
    Type: String
    Default: 'arn:aws:iam::297997107448:role/CodeBuildRole'
    Description: 'CodeBuild Service Role ARN'


Resources:

  # ---------------- CodeBuild Project----------------
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${PipelineName}-build'
      ServiceRole: !Ref CodeBuildRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        Image: !Ref ContainerImage
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: MODULE_PATH
            Type: PLAINTEXT
            Value: !Ref ModulePath
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref BuildSpec
      TimeoutInMinutes: 60

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref PipelineName
      RoleArn: !Ref CodePipelineRoleArn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucketName

      Variables:
        - Name: LANE
          DefaultValue: 'default'

      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref ConnectionArn
                FullRepositoryId: !Ref RepoName
                BranchName: !Ref BranchName
                OutputArtifactFormat: CODE_ZIP
                DetectChanges: false
              OutputArtifacts:
                - Name: SourceOut

        - Name: Build
          Actions:
            - Name: DockerBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: SourceOut
              OutputArtifacts:
                - Name: BuildOut

        - Name: Deploy
          Actions:
            - Name: CFNDeploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: SourceOut
                - Name: BuildOut
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: !Sub '${ServiceName}-#{variables.LANE}'
                TemplatePath: !Sub 'SourceOut::${TemplatePath}'
                TemplateConfiguration: 'BuildOut::cfn-params.json'
                RoleArn: !Ref CloudFormationDeployRoleArn
                Capabilities: 'CAPABILITY_IAM,CAPABILITY_NAMED_IAM'
                ParameterOverrides: !Sub |
                  {
                    "ServiceBase": "${ServiceName}",
                    "Lane": "#{variables.LANE}",
                    "SdRegistryId": "${SdRegistryId}"
                  }
      RestartExecutionOnUpdate: true

Outputs:
  PipelineNameOut:
    Value: !Ref PipelineName
  CodeBuildProjectOut:
    Value: !Ref CodeBuildProject