spring:
  application:
    name: web-app

# Web 服务配置
server:
  port: ${WEB_SERVER_PORT:8080}
  servlet:
    context-path: /

# gRPC 客户端配置
grpc:
  client:
    # UserService 客户端配置
    user-service:
      address: static://localhost:9091
      negotiationType: plaintext
    # OrderService 客户端配置
    order-service:
      address: static://localhost:9092
      negotiationType: plaintext

# 日志配置
logging:
  level:
    com.ddm.demo: DEBUG
    net.devh.boot.grpc: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:--}] %logger{36} - %msg%n"

---

spring:
  config:
    activate:
      on-profile: test

grpc:
  client:
    user-service:
      address: "dns://demo-user-service.test.local:9091"
    order-service:
      address: "dns://demo-order-service.test.local:9092"