AWSTemplateFormatVersion: '2010-09-09'
Description: 'Generic ECS Service + TaskDefinition'

Parameters:
  ServiceBase:
    Type: String
    Description: '服务基名，例如 order-api 或 user-api'
  Lane:
    Type: String
    Default: 'default'
    Description: '泳道名'
  ImageUri:
    Type: String
    Description: '容器镜像 URI（运行时传入）'
  DesiredCount:
    Type: Number
    Default: 1
  Cpu:
    Type: String
    Default: '512'
  Memory:
    Type: String
    Default: '1024'
  ContainerPort:
    Type: Number
    Default: 80
  ClusterName:
    Type: String
    Default: 'demo-cluster'
    Description: 'ECS 集群名称'
  ExecutionRoleArn:
    Type: String
    Default: 'arn:aws:iam::297997107448:role/ecsTaskExecutionRole'
    Description: 'ECS 任务执行角色（task execution role）'
  TaskRoleArn:
    Type: String
    Default: 'arn:aws:iam::297997107448:role/ecsTaskRole'
    Description: 'ECS 容器任务角色（task role）'
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Default: 'subnet-02c0811a961e428b5,subnet-0d3bc6916292f848c'
    Description: 'ECS Service 使用的子网 ID 列表'
  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: 'ECS Service 安全组 ID 列表'
    Default: 'sg-00a34a14c1889ddfc'
  AssignPublicIp:
    Type: String
    AllowedValues:
      - ENABLED
      - DISABLED
    Default: 'ENABLED'
    Description: '是否分配公有 IP（默认 ENABLED）'
  SdRegistryArn:
    Type: String
    Description: 'Cloud Map Service ARN（所有泳道可共用）'


Conditions:
  LaneIsDefault: !Equals [ !Ref Lane, 'default' ]
  LaneIsDash: !Equals [ !Ref Lane, '-' ]
  LaneIsNone: !Equals [ !Ref Lane, 'none' ]
  LaneIsNull: !Equals [ !Ref Lane, 'null' ]
  LaneShouldBeDefault: !Or
    - !Condition LaneIsDefault
    - !Condition LaneIsDash
    - !Condition LaneIsNone
    - !Condition LaneIsNull


Resources:
  TaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${ServiceBase}-task'
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: !Ref Cpu
      Memory: !Ref Memory
      ExecutionRoleArn: !Ref ExecutionRoleArn
      TaskRoleArn: !Ref TaskRoleArn
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      ContainerDefinitions:
        - Name: !Ref ServiceBase
          Image: !Ref ImageUri
          Essential: true
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              HostPort: !Ref ContainerPort
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub '/ecs/${ServiceBase}'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !If
                - LaneShouldBeDefault
                - 'default'
                - !Ref Lane

  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !If
        - LaneShouldBeDefault
        - !Sub '${ServiceBase}-default'
        - !Sub '${ServiceBase}-${Lane}'
      Cluster: !Ref ClusterName
      LaunchType: FARGATE
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDef
      DeploymentConfiguration:
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: !Ref Subnets
          SecurityGroups: !Ref SecurityGroups
          AssignPublicIp: !Ref AssignPublicIp
      ServiceRegistries:
        - RegistryArn: !Ref SdRegistryArn
      EnableECSManagedTags: true
      PropagateTags: SERVICE
      SchedulingStrategy: REPLICA
      DeploymentController:
        Type: ECS
      Tags: !If
        - LaneShouldBeDefault
        - !Ref 'AWS::NoValue'
        - - Key: Lane
            Value: !Ref Lane

Outputs:
  ServiceArn:
    Description: 'ECS Service ARN'
    Value: !Ref Service
  TaskDefinitionArn:
    Description: 'ECS TaskDefinition ARN'
    Value: !Ref TaskDef