AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Service + TaskDefinition (SRV registration via existing Cloud Map Namespace)'

Parameters:
  # ================= 基本参数 =================
  ServiceBase:
    Type: String
    Description: '服务基名（如 demo-rpc,web-api）'

  Lane:
    Type: String
    Default: 'default'
    Description: '泳道名（Pipeline 变量传入）'

  ImageUri:
    Type: String
    Description: '容器镜像 URI（由buildspec.yaml生成）'

  DesiredCount:
    Type: Number
    Default: 1
    Description: 'ECS Service 实例数'

  # ================= 资源规格 =================
  Cpu:
    Type: String
    Default: '512'
    Description: 'CPU 配额（单位：vCPU * 1024）'

  Memory:
    Type: String
    Default: '1024'
    Description: '内存配额（单位：MB）'

  # ================= 应用配置 =================
  AppEnv:
    Type: String
    Default: 'default'
    AllowedValues: [ default, dev, test, preonline, online ]
    Description: 'Spring Profile，对应 SPRING_PROFILES_ACTIVE'

  WebPort:
    Type: Number
    Default: 80
    Description: 'Web 服务端口'

  RpcPort:
    Type: Number
    Default: 8081
    Description: 'RPC 服务端口（注册到 Cloud Map SRV 记录）'

  # ================= 基础设施依赖 =================
  ClusterName:
    Type: String
    Default: 'demo-cluster'
    Description: 'ECS 集群名称'

  ExecutionRoleArn:
    Type: String
    Default: 'arn:aws:iam::297997107448:role/ecsTaskExecutionRole'
    Description: 'ECS 任务执行角色 (task execution role)'

  TaskRoleArn:
    Type: String
    Default: 'arn:aws:iam::297997107448:role/ecsTaskRole'
    Description: 'ECS 任务运行角色 (task role)'

  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Default: 'subnet-02c0811a961e428b5,subnet-0d3bc6916292f848c'
    Description: 'Service 使用的子网 ID 列表'

  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Default: 'sg-00a34a14c1889ddfc'
    Description: 'Service 使用的安全组 ID 列表'

  AssignPublicIp:
    Type: String
    AllowedValues: [ ENABLED, DISABLED ]
    Default: 'ENABLED'
    Description: '是否分配公有 IP'

  # ================= Cloud Map =================
  SdRegistryId:
    Type: String
    Description: 'Cloud Map Service Id（形如 srv-xxxx）'

# ================= 条件定义 =================
Conditions:
  LaneIsDefault: !Equals [ !Ref Lane, 'default' ]
  LaneIsEmpty: !Equals [ !Ref Lane, '' ]
  LaneAsDefault: !Or
    - !Condition LaneIsDefault
    - !Condition LaneIsEmpty

# ================= 资源定义 =================
Resources:

  # --- ECS 任务定义 ---
  TaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${ServiceBase}-task'
      RequiresCompatibilities: [ FARGATE ]
      NetworkMode: awsvpc
      Cpu: !Ref Cpu
      Memory: !Ref Memory
      ExecutionRoleArn: !Ref ExecutionRoleArn
      TaskRoleArn: !Ref TaskRoleArn
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      ContainerDefinitions:
        - Name: !Ref ServiceBase
          Image: !Ref ImageUri
          Essential: true
          PortMappings:
            - ContainerPort: !Ref WebPort
              Protocol: tcp
            - ContainerPort: !Ref RpcPort
              Protocol: tcp
          Environment:
            - Name: WEB_SERVER_PORT
              Value: !Ref WebPort
            - Name: RPC_SERVER_PORT
              Value: !Ref RpcPort
            - Name: SPRING_PROFILES_ACTIVE
              Value: !Ref AppEnv
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub '/ecs/${ServiceBase}'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !If
                - LaneAsDefault
                - 'default'
                - !Ref Lane

  # --- ECS 服务 ---
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !If
        - LaneAsDefault
        - !Sub '${ServiceBase}-default'
        - !Sub '${ServiceBase}-${Lane}'
      Cluster: !Ref ClusterName
      LaunchType: FARGATE
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDef
      DeploymentConfiguration:
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: !Ref Subnets
          SecurityGroups: !Ref SecurityGroups
          AssignPublicIp: !Ref AssignPublicIp
      ServiceRegistries:
        - RegistryId: !Ref SdRegistryId
          ContainerName: !Ref ServiceBase
          ContainerPort: !Ref RpcPort
      EnableECSManagedTags: true
      PropagateTags: SERVICE
      SchedulingStrategy: REPLICA
      DeploymentController:
        Type: ECS
      Tags: !If
        - LaneAsDefault
        - !Ref 'AWS::NoValue'
        - - Key: Lane
            Value: !Ref Lane

# ================= 输出 =================
Outputs:
  ServiceArn:
    Description: 'ECS Service ARN'
    Value: !Ref Service
  TaskDefinitionArn:
    Description: 'ECS TaskDefinition ARN'
    Value: !Ref TaskDef